### ISSUE TITLE
複数画像がある論文のdetailで画像へのアクセス性が悪い

### ISSUE THREAD

**Issue by 7oei** [enpitut2019/catchapp-front#43]
画像の境界をはっきりさせ任意の画像を簡単に拡大表示しできるようになってほしい

**Comment by sudame** [comment]
これ、つらみが深い
仮に100枚画像があったら100分割されて横並びになるのでほぼクリックできない

**Comment by sudame** [comment]
https://github.com/enpitut2019/catchapp-front/blob/000b7d9eace476354da952bc9a4b15e5be1f8a80/src/styles/paper.scss#L52-L71

**Comment by 7oei** [comment]
下にキャンプションのリスト表示してクリックするとその画像出てくるとかでも良いかも？
取り敢えずお客さんには画像が繋がって一枚しかないように見えるって言われてそれに関しては確かになって思った。
難しければ画像拡大の方で横スクロールできるようになればそれでだいぶ改善されそうなので放置してもらってもok

2020年1月21日(火) 14:06 Mikihiro SUDA <notifications@github.com>:
