### ISSUE TITLE
表示できないジャーナルの項目を消す

### ISSUE THREAD

**Issue by 7oei** [enpitut2019/catchapp-front#68]
いつもお世話になっております。

**Comment by sudame** [comment]
これどういう意味？
ジャーナルが取得できない場合は出しもしないってことかな

**Comment by 7oei** [comment]
あれ？ジャーナルってarXivAPIで取得不可能って話じゃなかったっけ？取れる奴は取れてるの？
前にジャーナルとるの厳しそうって話聞いた気がして、それなら項目残しておく意味もないかなって意味だったんだけど。

**Comment by sudame** [comment]
取れるやつは取れてるよ〜

**Comment by 7oei** [comment]
マジか。普通に知らなかった。closeする。
